"""Curated-submission write API (Gates 10 + 15).

Architecture D6 ships the auth gate at the middleware layer (Next.js side);
this layer enforces it server-side too. Anonymous / Tier 1 POSTs return 401
/ 403 respectively. ``request.user.access_tier`` carries the tier from the
DRF token session.

Architecture D10: shared throttle scope ``submissions_create``.
Security must-have #5: ``CreateModelMixin`` only — no list or retrieve
routes are auto-generated by the router because we don't register these
viewsets with the DRF router at all. We expose ``POST`` as a function-style
APIView via ``CreateAPIView`` to make the boundary explicit.
"""

from __future__ import annotations

import hashlib
from typing import Any

from django.conf import settings
from django.core.cache import cache
from django.core.mail import mail_managers
from django.utils.translation import gettext as _
from rest_framework import status
from rest_framework.generics import CreateAPIView
from rest_framework.request import Request
from rest_framework.response import Response

from accounts.permissions import TierPermission
from submissions.models import (
    HusbandryContribution,
    PopulationSubmission,
    SubmissionStatus,
)
from submissions.serializers import (
    HusbandryContributionCreateSerializer,
    PopulationSubmissionCreateSerializer,
)
from submissions.throttles import SubmissionsHourlyThrottle

# Daily cap (security must-have #3). Backs up the hourly DRF throttle —
# someone hitting the hourly limit every hour for 24 hours could still
# generate 240 submissions; we cap them at 20/day.
DAILY_CAP_PER_USER = 20
DAILY_CAP_WINDOW_SECONDS = 24 * 60 * 60


def _daily_cap_key(user_pk: int) -> str:
    """Cache key for the daily-submission counter. Truncated SHA for length."""
    pk_hash = hashlib.sha256(str(user_pk).encode()).hexdigest()[:16]
    return f"submission_daily_cap:{pk_hash}"


def _client_ip(request: Request) -> str:
    """Best-effort client IP for triage; matches accounts/views.py pattern."""
    if getattr(settings, "TRUST_X_FORWARDED_FOR", False):
        xff = request.META.get("HTTP_X_FORWARDED_FOR")
        if xff:
            return xff.split(",")[0].strip()
    return request.META.get("REMOTE_ADDR", "0.0.0.0")


class _BaseSubmissionCreateView(CreateAPIView):
    """Shared POST plumbing for both submission types.

    Subclasses set ``serializer_class`` and ``submission_type_label``.

    Permission: Tier 2+ session required. Anonymous → 401 via authentication;
    Tier 1 (hypothetical — default at signup is Tier 2 so this is defensive)
    → 403 via TierPermission(2).
    """

    permission_classes = [TierPermission(2)]
    throttle_classes = [SubmissionsHourlyThrottle]
    submission_type_label = "submission"  # subclass overrides
    feature_flag_setting = ""  # subclass overrides

    def create(self, request: Request, *args: Any, **kwargs: Any) -> Response:
        # Security must-have #2: Django-side env flag. The Next.js
        # NEXT_PUBLIC_FEATURE_CONTRIBUTE_* flag only gates the UI route —
        # without this check, a determined adversary could still POST
        # directly to the API while the feature is "off." When the
        # Django-side flag is False, the endpoint returns 404 to keep
        # the surface invisible (not 403, which would advertise existence).
        if self.feature_flag_setting and not getattr(settings, self.feature_flag_setting, False):
            return Response({"detail": _("Not found.")}, status=status.HTTP_404_NOT_FOUND)

        # Daily cap — second layer behind the DRF hourly throttle.
        # Architecture: separate cache.incr counter so the daily window
        # advances independently of the hourly one.
        cap_key = _daily_cap_key(request.user.pk)
        cache.add(cap_key, 0, timeout=DAILY_CAP_WINDOW_SECONDS)
        daily_count = cache.incr(cap_key)
        if daily_count > DAILY_CAP_PER_USER:
            return Response(
                {
                    "detail": _(
                        "You've reached the daily submission limit. Please try again tomorrow."
                    )
                },
                status=status.HTTP_429_TOO_MANY_REQUESTS,
            )

        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        # Honeypot — silent-spam path (security must-have #6).
        # Return 201 so the bot sees success and doesn't probe further;
        # the row gets status='spam' and no manager email fires.
        # Any non-empty value trips the trap, including whitespace —
        # the serializer's ``trim_whitespace=False`` preserves the raw
        # value so this check sees what the bot actually sent. The only
        # value that should pass through as legitimate is genuine
        # absence (field not in POST, or explicit empty string).
        honeypot = serializer.validated_data.pop("website", "")
        if honeypot:
            instance = serializer.save(
                submitter_user=request.user,
                submitter_ip=_client_ip(request),
                user_agent=request.META.get("HTTP_USER_AGENT", "")[:500],
                status=SubmissionStatus.SPAM,
            )
            # Match the 201 shape of a normal submission so the bot can't
            # distinguish success from honeypot-trip via response content.
            return Response(
                {"id": instance.pk, "status": SubmissionStatus.NEW.value},
                status=status.HTTP_201_CREATED,
            )

        instance = serializer.save(
            submitter_user=request.user,
            submitter_ip=_client_ip(request),
            user_agent=request.META.get("HTTP_USER_AGENT", "")[:500],
        )

        self._notify_managers(request=request, instance=instance)

        return Response(
            {"id": instance.pk, "status": instance.status},
            status=status.HTTP_201_CREATED,
        )

    def _notify_managers(self, *, request: Request, instance: Any) -> None:
        """Email platform managers on every non-spam submission.

        Reuses the path wired by PR #197 + #198. Locale of this email is
        always English (settings.LANGUAGE_CODE) — admin is one person and
        doesn't need locale-aware admin alerts. AC-15.19.
        """
        if not getattr(settings, "MANAGERS", None):
            return

        subject = f"New {self.submission_type_label}: {request.user.name} <{request.user.email}>"
        species_label = getattr(instance.species, "scientific_name", None) or "(no species)"
        body = (
            f"A Tier 2+ user submitted a {self.submission_type_label}.\n\n"
            f"Submitter: {request.user.name} <{request.user.email}>\n"
            f"Species:   {species_label}\n"
            f"Locale:    {request.user.locale}\n"
            f"Tier:      {request.user.access_tier}\n\n"
            f"Review queue: /admin/submissions/"
            f"{instance.__class__.__name__.lower()}/{instance.pk}/change/\n"
        )

        mail_managers(subject=subject, message=body, fail_silently=True)


class PopulationSubmissionCreateView(_BaseSubmissionCreateView):
    """POST /api/v1/contribute/populations/ — Gate 15."""

    serializer_class = PopulationSubmissionCreateSerializer
    queryset = PopulationSubmission.objects.none()  # required by DRF; never read
    submission_type_label = "population submission"
    feature_flag_setting = "CONTRIBUTE_POPULATION_ENABLED"


class HusbandryContributionCreateView(_BaseSubmissionCreateView):
    """POST /api/v1/contribute/husbandry/ — Gate 10 (reopened)."""

    serializer_class = HusbandryContributionCreateSerializer
    queryset = HusbandryContribution.objects.none()
    submission_type_label = "husbandry contribution"
    feature_flag_setting = "CONTRIBUTE_HUSBANDRY_ENABLED"
